[build]
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update && apt-get -y install apt-utils",
  "apt-get -y install libasound2-dev:$CROSS_DEB_ARCH portaudio19-dev:$CROSS_DEB_ARCH libdbus-1-dev:$CROSS_DEB_ARCH libpulse-dev:$CROSS_DEB_ARCH"
]
