name: Continuous Deployment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publishing ${{ matrix.build_target }}-${{ matrix.artifact_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_target: [macos, linux, linux-armhf]
        rust: [stable]
        artifact_type: ['slim', 'default', 'full']  # The build strategy will build all types for each OS specified
        include:
          - artifact_type: 'slim'               # Slim version has no features enabled by default.
            feature: ''
          - artifact_type: 'default'
            feature: 'dbus_keyring,dbus_mpris'  # Default version has all extra features enabled
          - artifact_type: 'full'
            feature: 'dbus_keyring,dbus_mpris'  # Full version has all extra features and audio backends enabled
          - build_target: macos
            os: macos-latest
            artifact_prefix: macos
            target: aarch64-apple-darwin
          - build_target: linux
            os: ubuntu-latest
            artifact_prefix: linux
            target: x86_64-unknown-linux-gnu
          - build_target: linux-armhf
            os: ubuntu-20.04
            artifact_prefix: linux-armhf
            target: arm-unknown-linux-gnueabihf
          - build_target: macos
            artifact_type: slim
            audio_backend: portaudio_backend
          - build_target: linux
            artifact_type: slim
            audio_backend: pulseaudio_backend
          - build_target: linux-armhf
            artifact_type: slim
            audio_backend: alsa_backend
          - build_target: macos
            artifact_type: default
            audio_backend: portaudio_backend
          - build_target: linux
            artifact_type: default
            audio_backend: pulseaudio_backend
          - build_target: linux-armhf
            artifact_type: default
            audio_backend: alsa_backend
          - build_target: linux
            artifact_type: full
            audio_backend: pulseaudio_backend,alsa_backend,rodio_backend
          - build_target: macos
            artifact_type: full
            audio_backend: portaudio_backend,rodio_backend
          - build_target: linux-armhf
            artifact_type: full
            audio_backend: alsa_backend

    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - name: Installing needed macOS dependencies
        if: matrix.os == 'macos-latest'
        run: brew install awk dbus pkg-config portaudio
      - name: Installing needed Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq libasound2-dev libssl-dev libpulse-dev libdbus-1-dev libc6-dev
          echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
      - name: Installing needed Ubuntu armhf dependencies
        if: matrix.os == 'ubuntu-20.04' && matrix.build_target == 'linux-armhf'
        run: |
          sudo mkdir -p /build/sysroot
          echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ focal main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y -qq gcc-arm-linux-gnueabihf build-essential pkg-config
          sudo apt-get download libasound2:armhf libasound2-dev:armhf libssl1.1:armhf libssl-dev:armhf
          # unpack debs to build root
          for f in *.deb; do sudo dpkg -x $f /build/sysroot/; done && sudo rm *.deb
          # fix symlinks of libraries
          find /build/sysroot/ -lname '/*' | while read -r link; do abs_target=$(readlink "$link"); sudo ln -fs "/build/sysroot$abs_target" "$link"; done
          echo "RUSTFLAGS=-C linker=arm-linux-gnueabihf-gcc -L/usr/arm-linux-gnueabihf/lib -L/build/sysroot/usr/lib/arm-linux-gnueabihf -L/build/sysroot/lib/arm-linux-gnueabihf" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/build/sysroot/usr/lib/arm-linux-gnueabihf/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_SYSROOT_DIR=/build/sysroot" >> $GITHUB_ENV
      - name: Installing needed Ubuntu armhf dependencies (full)
        if: matrix.os == 'ubuntu-20.04' && matrix.build_target == 'linux-armhf' && matrix.artifact_type != 'slim'
        run: |
          # Make dbus-rs cross-compile, see https://github.com/diwic/dbus-rs/issues/184#issuecomment-520228758
          sudo apt-get download libdbus-1-dev:armhf libdbus-1-3:armhf libsystemd0:armhf libsystemd-dev:armhf libgcrypt20:armhf libgcrypt20-dev:armhf liblzma5:armhf liblzma-dev:armhf liblz4-1:armhf liblz4-dev:armhf libgpg-error0:armhf libgpg-error-dev:armhf libzstd1:armhf libzstd-dev:armhf libcap2:armhf libcap-dev:armhf
          # unpack additional debs to build root
          for f in *.deb; do sudo dpkg -x $f /build/sysroot/; done && sudo rm *.deb
          # fix symlinks of libraries
          find /build/sysroot/ -lname '/*' | while read -r link; do abs_target=$(readlink "$link"); sudo ln -fs "/build/sysroot$abs_target" "$link"; done
          sudo mkdir -p /.cargo
          echo -e '[target.arm-unknown-linux-gnueabihf.dbus]\nrustc-link-lib = ["dbus-1", "gcrypt", "gpg-error", "lz4", "lzma", "systemd", "zstd", "cap"]' | sudo tee -a /.cargo/config.toml
      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Running cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          toolchain: ${{ matrix.rust }}
          args: --locked --release --target ${{ matrix.target }} --no-default-features --features "${{ matrix.feature }},${{ matrix.audio_backend }}"
      - name: Packaging final binary
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf spotifyd-${{ matrix.artifact_prefix }}-${{ matrix.artifact_type }}.tar.gz spotifyd
          shasum -a 512 spotifyd-${{ matrix.artifact_prefix }}-${{ matrix.artifact_type }}.tar.gz > spotifyd-${{ matrix.artifact_prefix }}-${{ matrix.artifact_type }}.sha512
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/spotifyd-${{ matrix.artifact_prefix }}-${{ matrix.artifact_type }}.tar.gz
            target/${{ matrix.target }}/release/spotifyd-${{ matrix.artifact_prefix }}-${{ matrix.artifact_type }}.sha512
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
