name: Continuous Deployment (new)

on:
  push:
    tags: 
      - 'v*.*.*'
    branches:
      - master
      - cd_rework_new

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run compose file
        run: |
          docker compose -f contrib/docker-compose.yml up

        
